pipeline:
  identifier: Build_teshruparelll_Prod_CI_CD_1723148492595
  name: Build Prod-CI-CD
  orgIdentifier: default
  projectIdentifier: ProdCICD
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: teshruparelll/Prod-CI-CD
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: account.DockerRepo
                    repo: hiteshreeruparell/demo
                    tags:
                      - Prod-CI-CD
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
